### ISSUE TITLE
The OR condition is not getting evaluated in a nested loop.

### ISSUE THREAD

**Issue by tanmay-banerjee** [nire0510/kenolo#1]
Trying to Achieve:

(a.b=c and a1.b1=c1) and ((a2.b2=c2 or a3.b3=c3) and (a4.b4=c4 and a5.b5=c5 and ((a6.b6=c6 and a7.b7=c7) and ( (a8.b8=c8 or a9.b9=c9) or (a10.b10=c10 and a11.b11=c11) or (a12.b12=c12 or a13.b13=c13 or a14.b14=c14) ))))

with the Rules JSON format as:
"RuleSet1": {
		"include": {
			"and": [{
					"name": "Rule_1",
					"property": "CIF.Document.Verification",
					"operator": "eq",
					"value": "No"
				},
				{
					"name": "Rule_1.1",
					"property": "CIF.Document.Verification",
					"operator": "eq",
					"value": "No"
				},
				{
					"or": [{
							"name": "Rule_1.1.1",
							"property": "CIF.Document.Verification",
							"operator": "eq",
							"value": "No"
						},
						{
							"name": "Rule_1.1.2",
							"property": "CIF.Document.Verification",
							"operator": "eq",
							"value": "No"
						}],
					"and": [{
							"name": "Rule_1.1.3",
							"property": "CIF.Document.Verification",
							"operator": "eq",
							"value": "No"
							},
							{
								"name": "Rule_1.1.4",
								"property": "CIF.Document.Verification",
								"operator": "eq",
								"value": "No"
							},
							{"and": [{
										"name": "Rule_1.1.4.1",
										"property": "CIF.Document.Verification",
										"operator": "eq",
										"value": "No"
									},
									{
										"name": "Rule_1.1.4.2",
										"property": "CIF.Document.Verification",
										"operator": "eq",
										"value": "No"
									},
									{
										"or": [{
											"name": "Rule_1.1.4.2.1",
											"property": "CIF.Document.Verification",
											"operator": "eq",
											"value": "No"
											},
											{
												"name": "Rule_1.1.4.2.2",
												"property": "CIF.Document.Verification",
												"operator": "eq",
												"value": "No"
											},
											{"and":[{
													"name": "Rule_1.1.4.2.1.1",
													"property": "CIF.Document.Verification",
													"operator": "eq",
													"value": "No"
													},
													{
														"name": "Rule_1.1.4.2.1.2",
														"property": "CIF.Document.Verification",
														"operator": "eq",
														"value": "No"
													}],
												"or":[{
														"name": "Rule_1.1.4.2.1.3.1",
														"property": "CIF.Document.Verification",
														"operator": "eq",
														"value": "No"	
													},
													{
														"name": "Rule_1.1.4.2.1.3.2",
														"property": "CIF.Document.Verification",
														"operator": "eq",
														"value": "No"	
													},
													{
														"name": "Rule_1.1.4.2.1.3.3",
														"property": "CIF.Document.Verification",
														"operator": "eq",
														"value": "No"	
												}]
											}]
							}]
				}]
		}
	}
};

Data as:
"{"CIF": {"Event": "New","Document": {"Verification": "No","Information": "Inconsistent"}}}";

Actual Result is:
Rule_1,Rule_1.1,Rule_1.1.3,Rule_1.1.4,Rule_1.1.4.1,Rule_1.1.4.2,Rule_1.1.4.2.1

Expected is:
Rule_1,Rule_1.1,**Rule_1.1.1**,Rule_1.1.3,Rule_1.1.4,Rule_1.1.4.1,Rule_1.1.4.2,Rule_1.1.4.2.1

The one Emboldened is missing.

**Comment by nire0510** [comment]
That's a nice catch, thanks 👍 
What was happening is that the rule contained both OR and AND operators. Since JSON objects are sorted alphabetically by default, Kenolo evaluated the AND operator first, and since it return true, it didn't proceed (which is a good thing, basically).
But since the wrong order evaluation is not a desirable behavior, I have made a small change in code and your scenario is now valid. See v2.0.0.
